# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=50, unique=True)),
                ('id_type', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=70)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('initiated_on', models.DateTimeField(auto_now_add=True)),
                ('confirmed_on', models.DateTimeField(null=True)),
                ('member', models.CharField(max_length=70)),
                ('constituency', models.CharField(max_length=50)),
            ],
        ),
    ]
