# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member_name',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=set([('member_id', 'id_type')]),
        ),
    ]
