# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171129_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_pin', models.CharField(max_length=10)),
                ('member_id', models.CharField(max_length=50)),
                ('member_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
