# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180107_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='date_registered',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
